# HTTP 요청 차단
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # 모든 요청 차단
    return 444;
}

# HTTPS 요청 차단 (인증서 없이)
server {
    listen 443 default_server;
    listen [::]:443 default_server;

    server_name _;

    # 모든 요청 차단
    return 444;
}

# server {
#     listen 80 default_server;
#     listen [::]:80 default_server;

#     server_name _;

#     # 모든 요청 차단
#     include /etc/nginx/snippets/global-error-pages.conf;
# }
