location @global_404 {
    internal;
    root    /var/nginx/static/errors;
    try_files /404.html =404;
    # add_header X-Error-Source "global-fallback" always;
}

location @global_50x {
    root    /var/nginx/static/errors;
    try_files /503.html =503;
    # add_header X-Error-Source "global-fallback" always;
    add_header Retry-After 3600 always;
    add_header Cache-Control "no-cache";
}